const CATEGORIES_ACTION_TYPE={
    FETCH_CATEGORIES_START: 'categoreis/FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS:'categories/FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED:'categories/FETCH_CATEGORIES_FAILED'
}

export default CATEGORIES_ACTION_TYPE;